/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.accionesSobreTabla;

import Spotifoo.Admin;
import Spotifoo.Artista;
import Spotifoo.DataManager.DAO_FS;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import static javax.swing.GroupLayout.Alignment.BASELINE;
import static javax.swing.GroupLayout.Alignment.LEADING;
import static javax.swing.GroupLayout.Alignment.TRAILING;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nicolaz999
 */
public class ventanaEditarArtista extends javax.swing.JFrame {

    JTable tableVentanaArtista;
    Admin admin;
    JTable table;
    JButton aplicarButton;
    Artista artista;

    public ventanaEditarArtista(JTable table,Admin admin) {
        initComponents();
        this.tableVentanaArtista = table;
        this.admin = admin;
        configFrame();
        generarLayout();
        setTableRow();
        eventosComponentes();
    }
    private void configFrame() {
        this.setTitle("Spotifoo");
        setSize(800, 200);
        setLocationRelativeTo(null);
        getContentPane().setLayout(new BoxLayout(getContentPane(),BoxLayout.Y_AXIS));
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); 
    }

    private void generarLayout() {
        String[] columnNames={"Nombre", "Genero","Año"};
        Object[][] data = {};
        table = new JTable(data,columnNames);
        TableModel model = new DefaultTableModel(data,columnNames){
            @Override
            public boolean isCellEditable(int row,int column){
                return true;
            }
        };
        table.setModel(model);
        table.setPreferredScrollableViewportSize(new Dimension(70, 70));
        JScrollPane scrollPane = new JScrollPane(table);
        
        aplicarButton = new JButton("Aplicar");
        
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        layout.setHorizontalGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane))
                    .addComponent(aplicarButton))
        );
        layout.setVerticalGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(BASELINE)
                .addComponent(scrollPane))
            .addGroup(layout.createParallelGroup(LEADING)
                .addComponent(aplicarButton))
        );
    }

    private void eventosComponentes() {
        aplicarButton.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            aplicarButtonActionPerformed(evt);
        }

        private void aplicarButtonActionPerformed(ActionEvent evt) {
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            DefaultTableModel modelVentanaArtista = (DefaultTableModel) tableVentanaArtista.getModel();
            
            for(int j=0 ; j < tableVentanaArtista.getRowCount();j++){
                    if (modelVentanaArtista.getValueAt(j, 1).equals(artista.getNombre()))
                        modelVentanaArtista.removeRow(j);
                }
            artista.setAñoFormacion((Integer)model.getValueAt(0, 2));
            artista.setGenero((String) model.getValueAt(0, 1));
            artista.setNombre((String) model.getValueAt(0, 0));
            
            admin.addArtista(artista);
            modelVentanaArtista.addRow(new Object[]{artista.getId(),artista.getNombre()});
        }
    });
    }

    private void setTableRow(){
        DefaultTableModel model = (DefaultTableModel) tableVentanaArtista.getModel();
        artista = DAO_FS.getBaseDatos().getArtista((Integer)model.getValueAt(tableVentanaArtista.getSelectedRow(), 0));

        model = (DefaultTableModel) table.getModel();
        model.addRow(new Object[]{artista.getNombre(),artista.getGenero(),
            artista.getAñoFormacion()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
